version: '3.1'
services:
  web:
    build:
      context: .
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: postgres:9.6.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: culture